# Generated by Django 6.0 on 2025-12-09 11:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200, verbose_name='title')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'title',
                'verbose_name_plural': 'log title',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_text', models.TextField(verbose_name='log content')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated at')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='wlog.title', verbose_name='title to which')),
            ],
            options={
                'verbose_name': 'log entry',
                'verbose_name_plural': 'log entries',
                'ordering': ['created_at'],
            },
        ),
    ]
