# Generated by Django 6.0 on 2025-12-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wlog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="log",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "log entry",
                "verbose_name_plural": "log entries",
            },
        ),
    ]
