# Generated by Django 6.0 on 2025-12-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wlog", "0002_alter_log_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="log",
            options={
                "ordering": ["created_at"],
                "verbose_name": "log entry",
                "verbose_name_plural": "log entries",
            },
        ),
    ]
