# Generated by Django 6.0 on 2025-12-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wlog", "0003_alter_log_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="title",
            options={
                "ordering": ["created_at"],
                "verbose_name": "title",
                "verbose_name_plural": "log title",
            },
        ),
    ]
